name: release
on:
  push:
    branches:
      - develop

jobs:
  publish-spring:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish Container Image with gradle
        run: |
          ./gradlew :kitiler-spring-application:buildImage \
            --parallel \
            --continue \
            -Pimage.native.enabled=false \
            -Pimage.registry.publish.username=${{github.actor}} \
            -Pimage.registry.publish.password=${{secrets.GITHUB_TOKEN}} \
            -Pimage.name=ghcr.io/tronto20/kitiler \
            -Pimage.tags=spring-${{ github.ref_name }}-${{ github.run_id }} \
            -Pimage.push=true

  publish-spring-native:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish Container Image with gradle
        run: |
          ./gradlew :kitiler-spring-application:buildImage \
            --parallel \
            --continue \
            -Pimage.registry.publish.username=${{github.actor}} \
            -Pimage.registry.publish.password=${{secrets.GITHUB_TOKEN}} \
            -Pimage.name=ghcr.io/tronto20/kitiler \
            -Pimage.tags=spring-${{ github.ref_name }}-${{ github.run_id }} \
            -Pimage.push=true
