name: 'test PR'

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew build --parallel --continue


  publish-spring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish Container Image with gradle
        run: |
          ./gradlew :kitiler-spring-application:buildImage \
            --parallel \
            --continue \
            -Pimage.native.enabled=false \
            -Pimage.name=ghcr.io/tronto20/kitiler \
            -Pimage.tags=spring-latest,spring-{VERSION} \
            -Pimage.push=false

  publish-spring-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish Container Image with gradle
        run: |
          ./gradlew :kitiler-spring-application:buildImage \
            --parallel \
            --continue \
            -Pimage.name=ghcr.io/tronto20/kitiler \
            -Pimage.tags=spring-native-latest,spring-native-{VERSION},latest,{VERSION} \
            -Pimage.push=false
