name: 'test PR'

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew build --parallel --continue
